export const staticData = [
    {
        first_name: "Gautam",
        last_name: "Nagpal",
        email: "gautam@gmail.com",
        phone: "9876543210",
        image: "",
    },
    {
        first_name: "test",
        last_name: "1",
        email: "test@gmail.com",
        phone: "9876543210",
        image: "",
    },
    {
        first_name: "Testing ,12",
        last_name: " Data",
        email: "testing@gmail.com",
        phone: "9876543210",
        image: "",
    },
    {
        first_name: "Gautam 123",
        last_name: "Nagpal",
        email: "gautam@gmail.com",
        phone: "9876543210",
        image: "",
    },
    {
        first_name: "test 123",
        last_name: "1",
        email: "test@gmail.com",
        phone: "9876543210",
        image: "",
    },
    {
        first_name: "Testing 654",
        last_name: " Data",
        email: "testing@gmail.com",
        phone: "9876543210",
        image: "",
    },
    {
        first_name: " 111111 Gautam",
        last_name: "Nagpal",
        email: "gautam@gmail.com",
        phone: "9876543210",
        image: "",
    },
    {
        first_name: "1356 test",
        last_name: "1",
        email: "test@gmail.com",
        phone: "9876543210",
        image: "",
    },
    {
        first_name: "456Testing",
        last_name: " Data",
        email: "testing@gmail.com",
        phone: "9876543210",
        image: "",
    },
    {
        first_name: "ascascasc",
        last_name: "Nagpal",
        email: "gautam@gmail.com",
        phone: "9876543210",
        image: "",
    },
    {
        first_name: "ascasctest",
        last_name: "1",
        email: "test@gmail.com",
        phone: "9876543210",
        image: "",
    },
    {
        first_name: "56423",
        last_name: " Data",
        email: "testing@gmail.com",
        phone: "9876543210",
        image: "",
    },
    {
        first_name: "56423",
        last_name: " Data",
        email: "testing@gmail.com",
        phone: "9876543210",
        image: "",
    }
]